// Code generated by tools/generate-definitions.mjs. DO NOT EDIT.

package connparse

func BuiltInDefinitions() []Definition {
	return []Definition{
		Definition{
			ID:      "clickhouse",
			Name:    "ClickHouse",
			Type:    "database",
			Schemes: []string{"clickhouse", "ch"},
			Adapter: "clickhouse",
			Defaults: map[string]any{
				"port": 9000,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type: "database",
			},
			PathRule: Rule{
				Type: "object_path",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"createDatabaseIfNotExist": QueryRule{
					Type: "boolean",
				},
				"database": QueryRule{
					Type: "string",
				},
				"debug": QueryRule{
					Type: "boolean",
				},
				"password": QueryRule{
					Type: "string",
				},
				"readonly": QueryRule{
					Type: "number",
				},
				"ssl": QueryRule{
					Type: "boolean",
				},
				"sslmode": QueryRule{
					Type: "string",
				},
				"user": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "cockroachdb",
			Name:    "CockroachDB",
			Type:    "database",
			Schemes: []string{"cockroach", "cockroachdb"},
			Adapter: "postgres-compatible",
			Defaults: map[string]any{
				"port": 26257,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type: "database",
			},
			PathRule: Rule{
				Type: "object_path",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"application_name": QueryRule{
					Type: "string",
				},
				"options": QueryRule{
					Type: "string",
				},
				"password": QueryRule{
					Type: "string",
				},
				"results_buffer_size": QueryRule{
					Type: "string",
				},
				"sslcert": QueryRule{
					Type: "string",
				},
				"sslkey": QueryRule{
					Type: "string",
				},
				"sslmode": QueryRule{
					Type:    "string",
					Allowed: []any{"disable", "allow", "prefer", "require", "verify-ca", "verify-full"},
				},
				"sslrootcert": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
			Options: map[string]any{
				"compatible_with": "postgres",
			},
		},
		Definition{
			ID:        "duckdb",
			Name:      "DuckDB",
			Type:      "database",
			Schemes:   []string{"duckdb"},
			Adapter:   "duckdb",
			Authority: map[string]any{},
			ResourceRule: Rule{
				Type:     "database",
				Required: true,
			},
			PathRule: Rule{
				Type:     "filesystem_path",
				Required: true,
			},
			CredentialsRule: map[string]any{},
			QueryParameters: map[string]QueryRule{
				"access_mode": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{},
		},
		Definition{
			ID:      "elasticsearch",
			Name:    "Elasticsearch",
			Type:    "api",
			Schemes: []string{"elasticsearch", "elastic", "elasticsearch+http", "elasticsearch+https"},
			Adapter: "elasticsearch",
			Defaults: map[string]any{
				"port": 9200,
			},
			Authority: map[string]any{
				"host": true,
				"port": true,
			},
			ResourceRule: Rule{
				Type: "index",
			},
			PathRule: Rule{
				Type: "api_path",
			},
			CredentialsRule: map[string]any{
				"api_key":  true,
				"password": true,
				"token":    true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"apiKey": QueryRule{
					Type: "string",
				},
				"api_key": QueryRule{
					Type: "string",
				},
				"token": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "file",
			Name:    "File",
			Type:    "file",
			Schemes: []string{"file"},
			Adapter: "file",
			Authority: map[string]any{
				"host": false,
			},
			ResourceRule: Rule{
				Type: "none",
			},
			PathRule: Rule{
				Type:     "filesystem_path",
				Required: true,
			},
			CredentialsRule: map[string]any{},
			QueryParameters: map[string]QueryRule{},
			Validation:      ValidationRule{},
		},
		Definition{
			ID:      "mariadb",
			Name:    "MariaDB",
			Type:    "database",
			Schemes: []string{"mariadb"},
			Adapter: "mysql-compatible",
			Defaults: map[string]any{
				"port": 3306,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type: "database",
			},
			PathRule: Rule{
				Type: "object_path",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"password": QueryRule{
					Type: "string",
				},
				"ssl": QueryRule{
					Type: "string",
				},
				"sslMode": QueryRule{
					Type:    "string",
					Allowed: []any{"disable", "trust", "verify-ca", "verify-full"},
				},
				"user": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "memcached",
			Name:    "Memcached",
			Type:    "cache",
			Schemes: []string{"memcached", "memcacheds"},
			Adapter: "memcached",
			Defaults: map[string]any{
				"port": 11211,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type: "none",
			},
			PathRule: Rule{
				Type: "none",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "mongodb",
			Name:    "MongoDB",
			Type:    "database",
			Schemes: []string{"mongodb", "mongodb+srv"},
			Adapter: "mongodb",
			Defaults: map[string]any{
				"port": 27017,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type: "database",
			},
			PathRule: Rule{
				Type: "collection",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"authMechanism": QueryRule{
					Type: "string",
				},
				"authMechanismProperties": QueryRule{
					Type: "string",
				},
				"authSource": QueryRule{
					Type: "string",
				},
				"connectTimeoutMS": QueryRule{
					Type: "number",
				},
				"directConnection": QueryRule{
					Type: "boolean",
				},
				"replicaSet": QueryRule{
					Type: "string",
				},
				"retryWrites": QueryRule{
					Type: "boolean",
				},
				"serverSelectionTimeoutMS": QueryRule{
					Type: "number",
				},
				"ssl": QueryRule{
					Type: "boolean",
				},
				"tls": QueryRule{
					Type: "boolean",
				},
				"tlsCAFile": QueryRule{
					Type: "string",
				},
				"tlsCertificateKeyFile": QueryRule{
					Type: "string",
				},
				"tlsInsecure": QueryRule{
					Type: "boolean",
				},
				"w": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "mysql",
			Name:    "MySQL",
			Type:    "database",
			Schemes: []string{"mysql", "mysqlx", "mysqlx+srv"},
			Adapter: "mysql-compatible",
			Defaults: map[string]any{
				"port": 3306,
			},
			Authority: map[string]any{
				"host": true,
				"port": true,
			},
			ResourceRule: Rule{
				Type: "database",
			},
			PathRule: Rule{
				Type: "object_path",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"auth-method": QueryRule{
					Type:    "string",
					Allowed: []any{"AUTO", "MYSQL41", "SHA256_MEMORY", "FROM_CAPABILITIES", "FALLBACK", "PLAIN"},
				},
				"charset": QueryRule{
					Type: "string",
				},
				"get-server-public-key": QueryRule{
					Type: "boolean",
				},
				"schema": QueryRule{
					Type: "string",
				},
				"ssl": QueryRule{
					Type: "string",
				},
				"ssl-ca": QueryRule{
					Type: "string",
				},
				"ssl-capath": QueryRule{
					Type: "string",
				},
				"ssl-cert": QueryRule{
					Type: "string",
				},
				"ssl-cipher": QueryRule{
					Type: "string",
				},
				"ssl-crl": QueryRule{
					Type: "string",
				},
				"ssl-crlpath": QueryRule{
					Type: "string",
				},
				"ssl-key": QueryRule{
					Type: "string",
				},
				"ssl-mode": QueryRule{
					Type:    "string",
					Allowed: []any{"DISABLED", "PREFERRED", "REQUIRED", "VERIFY_CA", "VERIFY_IDENTITY"},
				},
				"tls-version": QueryRule{
					Type: "string",
				},
				"tls-versions": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "postgres",
			Name:    "PostgreSQL",
			Type:    "database",
			Schemes: []string{"postgres", "postgresql"},
			Adapter: "postgres-compatible",
			Defaults: map[string]any{
				"port": 5432,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type:     "database",
				Required: true,
			},
			PathRule: Rule{
				Type: "object_path",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"application_name": QueryRule{
					Type: "string",
				},
				"connect_timeout": QueryRule{
					Type: "number",
				},
				"host": QueryRule{
					Type: "string",
				},
				"hostaddr": QueryRule{
					Type: "string",
				},
				"options": QueryRule{
					Type: "string",
				},
				"passfile": QueryRule{
					Type: "string",
				},
				"password": QueryRule{
					Type: "string",
				},
				"port": QueryRule{
					Type: "string",
				},
				"require_auth": QueryRule{
					Type: "string",
				},
				"service": QueryRule{
					Type: "string",
				},
				"sslcert": QueryRule{
					Type: "string",
				},
				"sslkey": QueryRule{
					Type: "string",
				},
				"sslmode": QueryRule{
					Type:    "string",
					Allowed: []any{"disable", "allow", "prefer", "require", "verify-ca", "verify-full"},
				},
				"sslrootcert": QueryRule{
					Type: "string",
				},
				"target_session_attrs": QueryRule{
					Type:    "string",
					Allowed: []any{"any", "read-write", "read-only", "primary", "standby", "prefer-standby"},
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "questdb",
			Name:    "QuestDB",
			Type:    "database",
			Schemes: []string{"questdb"},
			Adapter: "questdb",
			Defaults: map[string]any{
				"port": 8812,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type: "database",
			},
			PathRule: Rule{
				Type: "object_path",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"token":    true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"auto_flush": QueryRule{
					Type:    "string",
					Allowed: []any{"on", "off"},
				},
				"auto_flush_interval": QueryRule{
					Type: "number",
				},
				"auto_flush_rows": QueryRule{
					Type: "number",
				},
				"init_buf_size": QueryRule{
					Type: "number",
				},
				"max_buf_size": QueryRule{
					Type: "number",
				},
				"protocol_version": QueryRule{
					Type: "string",
				},
				"request_min_throughput": QueryRule{
					Type: "number",
				},
				"request_timeout": QueryRule{
					Type: "number",
				},
				"retry_timeout": QueryRule{
					Type: "number",
				},
				"tls_roots": QueryRule{
					Type: "string",
				},
				"tls_roots_password": QueryRule{
					Type: "string",
				},
				"tls_verify": QueryRule{
					Type:    "string",
					Allowed: []any{"on", "unsafe_off"},
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "redis",
			Name:    "Redis",
			Type:    "cache",
			Schemes: []string{"redis", "rediss"},
			Adapter: "redis",
			Defaults: map[string]any{
				"port": 6379,
			},
			Authority: map[string]any{
				"host": true,
				"port": true,
			},
			ResourceRule: Rule{
				Type: "database_index",
			},
			PathRule: Rule{
				Type: "none",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"protocol": QueryRule{
					Type: "number",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
		},
		Definition{
			ID:      "s3",
			Name:    "Amazon S3",
			Type:    "object_storage",
			Schemes: []string{"s3"},
			Adapter: "s3",
			Authority: map[string]any{
				"bucket": true,
				"region": true,
			},
			ResourceRule: Rule{
				Type:     "bucket",
				Required: true,
			},
			PathRule: Rule{
				Type: "object_key",
			},
			CredentialsRule: map[string]any{},
			QueryParameters: map[string]QueryRule{
				"region": QueryRule{
					Type: "string",
				},
				"versionId": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{},
		},
		Definition{
			ID:        "sqlite",
			Name:      "SQLite",
			Type:      "database",
			Schemes:   []string{"sqlite"},
			Adapter:   "sqlite",
			Authority: map[string]any{},
			ResourceRule: Rule{
				Type:     "database",
				Required: true,
			},
			PathRule: Rule{
				Type:     "filesystem_path",
				Required: true,
			},
			CredentialsRule: map[string]any{},
			QueryParameters: map[string]QueryRule{
				"cache": QueryRule{
					Type: "string",
				},
				"mode": QueryRule{
					Type: "string",
				},
			},
			Validation: ValidationRule{},
		},
		Definition{
			ID:      "yugabytedb",
			Name:    "YugabyteDB",
			Type:    "database",
			Schemes: []string{"yugabyte", "yugabytedb"},
			Adapter: "postgres-compatible",
			Defaults: map[string]any{
				"port": 5433,
			},
			Authority: map[string]any{
				"host":       true,
				"multi_host": true,
				"port":       true,
			},
			ResourceRule: Rule{
				Type: "database",
			},
			PathRule: Rule{
				Type: "object_path",
			},
			CredentialsRule: map[string]any{
				"password": true,
				"username": true,
			},
			QueryParameters: map[string]QueryRule{
				"loadBalance": QueryRule{
					Type: "string",
				},
				"ssl": QueryRule{
					Type: "boolean",
				},
				"sslmode": QueryRule{
					Type:    "string",
					Allowed: []any{"disable", "allow", "prefer", "require", "verify-ca", "verify-full"},
				},
				"sslrootcert": QueryRule{
					Type: "string",
				},
				"topologyKeys": QueryRule{
					Type: "string",
				},
				"ybServersRefreshInterval": QueryRule{
					Type: "number",
				},
			},
			Validation: ValidationRule{
				RequireHost: true,
				PortRange: PortRange{
					Min: 1,
					Max: 65535,
				},
			},
			Options: map[string]any{
				"compatible_with": "postgres",
			},
		},
	}
}
