# Code generated by tools/generate-definitions.mjs. DO NOT EDIT.

from __future__ import annotations

from .types import ConnparseDefinition

BUILT_IN_DEFINITIONS: list[ConnparseDefinition] = [
  {
    "adapter": "object-storage",
    "authority": {
      "account": True,
      "host": True,
    },
    "credentials": {
      "access_key": True,
      "password": True,
      "secret_key": True,
      "token": True,
      "username": True,
    },
    "id": "adlsgen2",
    "name": "Azure Data Lake Storage",
    "options": {
      "provider": "azure",
    },
    "path": {
      "required": False,
      "type": "object_key",
    },
    "query_parameters": {
      "account_key": {
        "type": "string",
      },
      "auth_method": {
        "type": "string",
      },
      "client_id": {
        "type": "string",
      },
      "client_secret": {
        "type": "string",
      },
      "sas": {
        "type": "string",
      },
      "tenant_id": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "access_key",
        "secret_key",
        "token",
        "client_secret",
        "account_key",
        "sas",
      ],
    },
    "resource": {
      "required": False,
      "type": "filesystem",
    },
    "schemes": [
      "adls",
      "adlsgen2",
      "abfs",
      "abfss",
    ],
    "type": "object_storage",
    "validation": {
      "require_host": True,
    },
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 3306,
    },
    "id": "apache-doris",
    "name": "Apache Doris",
    "options": {
      "compatible_with": "mysql",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "charset": {
        "type": "string",
      },
      "ssl": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "apache-doris",
      "doris",
    ],
    "type": "analytics",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "region": True,
    },
    "credentials": {
      "access_key": True,
      "password": True,
      "secret_key": True,
      "token": True,
      "username": True,
    },
    "id": "athena",
    "name": "Amazon Athena",
    "path": {
      "required": False,
      "type": "table_path",
    },
    "query_parameters": {
      "catalog": {
        "type": "string",
      },
      "output_location": {
        "type": "string",
      },
      "region": {
        "type": "string",
      },
      "workgroup": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "access_key",
        "secret_key",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "athena",
    ],
    "type": "analytics",
    "validation": {
      "require_host": False,
    },
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 3306,
    },
    "id": "aurora-mysql",
    "name": "Aurora MySQL",
    "options": {
      "compatible_with": "mysql",
      "provider": "aws",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "charset": {
        "type": "string",
      },
      "ssl": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "aurora-mysql",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5432,
    },
    "id": "aurora-postgres",
    "name": "Aurora PostgreSQL",
    "options": {
      "compatible_with": "postgres",
      "provider": "aws",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "aurora-postgres",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "object-storage",
    "authority": {
      "account": True,
      "host": True,
    },
    "credentials": {
      "access_key": True,
      "password": True,
      "secret_key": True,
      "token": True,
      "username": True,
    },
    "id": "azure-blob",
    "name": "Azure Blob",
    "options": {
      "provider": "azure",
    },
    "path": {
      "required": False,
      "type": "blob",
    },
    "query_parameters": {
      "account_key": {
        "type": "string",
      },
      "auth_method": {
        "type": "string",
      },
      "client_id": {
        "type": "string",
      },
      "client_secret": {
        "type": "string",
      },
      "sas": {
        "type": "string",
      },
      "tenant_id": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "access_key",
        "secret_key",
        "token",
        "client_secret",
        "account_key",
        "sas",
      ],
    },
    "resource": {
      "required": False,
      "type": "container",
    },
    "schemes": [
      "azureblob",
      "azblob",
    ],
    "type": "object_storage",
    "validation": {
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 443,
    },
    "id": "azure-cosmosdb",
    "name": "Azure Cosmos DB",
    "options": {
      "provider": "azure",
    },
    "path": {
      "required": False,
      "type": "collection",
    },
    "query_parameters": {
      "auth_method": {
        "type": "string",
      },
      "client_id": {
        "type": "string",
      },
      "client_secret": {
        "type": "string",
      },
      "container": {
        "type": "string",
      },
      "tenant_id": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
        "client_secret",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "cosmosdb",
      "azure-cosmosdb",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "object-storage",
    "authority": {
      "account": True,
      "host": True,
    },
    "credentials": {
      "access_key": True,
      "password": True,
      "secret_key": True,
      "token": True,
      "username": True,
    },
    "id": "azure-files",
    "name": "Azure Files",
    "options": {
      "provider": "azure",
    },
    "path": {
      "required": False,
      "type": "file_path",
    },
    "query_parameters": {
      "account_key": {
        "type": "string",
      },
      "auth_method": {
        "type": "string",
      },
      "client_id": {
        "type": "string",
      },
      "client_secret": {
        "type": "string",
      },
      "sas": {
        "type": "string",
      },
      "tenant_id": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "access_key",
        "secret_key",
        "token",
        "client_secret",
        "account_key",
        "sas",
      ],
    },
    "resource": {
      "required": False,
      "type": "share",
    },
    "schemes": [
      "azurefile",
      "azurefiles",
    ],
    "type": "object_storage",
    "validation": {
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 9042,
    },
    "id": "azure-managed-cassandra",
    "name": "Azure Managed Cassandra",
    "options": {
      "compatible_with": "cassandra",
      "provider": "azure",
    },
    "path": {
      "required": False,
      "type": "table_path",
    },
    "query_parameters": {
      "consistency": {
        "type": "string",
      },
      "datacenter": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "keyspace",
    },
    "schemes": [
      "azure-managed-cassandra",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "redis",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 10000,
    },
    "id": "azure-managed-redis",
    "name": "Azure Managed Redis",
    "options": {
      "compatible_with": "redis",
      "provider": "azure",
      "tls": True,
    },
    "path": {
      "required": False,
      "type": "none",
    },
    "query_parameters": {
      "protocol": {
        "type": "number",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database_index",
    },
    "schemes": [
      "azure-managed-redis",
      "azure-managed-rediss",
    ],
    "type": "cache",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "project": True,
      "region": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "id": "bigquery",
    "name": "BigQuery",
    "path": {
      "required": False,
      "type": "table_path",
    },
    "query_parameters": {
      "access_token": {
        "type": "string",
      },
      "location": {
        "type": "string",
      },
      "region": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
        "access_token",
      ],
    },
    "resource": {
      "required": False,
      "type": "dataset",
    },
    "schemes": [
      "bigquery",
    ],
    "type": "analytics",
    "validation": {
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 443,
    },
    "id": "business-central",
    "name": "Dynamics 365 Business Central",
    "options": {
      "provider": "microsoft",
    },
    "path": {
      "required": False,
      "type": "api_path",
    },
    "query_parameters": {
      "auth_method": {
        "type": "string",
      },
      "client_id": {
        "type": "string",
      },
      "client_secret": {
        "type": "string",
      },
      "environment": {
        "type": "string",
      },
      "tenant_id": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
        "client_secret",
      ],
    },
    "resource": {
      "required": False,
      "type": "environment",
    },
    "schemes": [
      "businesscentral",
      "business-central",
    ],
    "type": "api",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 9042,
    },
    "id": "cassandra",
    "name": "Cassandra",
    "path": {
      "required": False,
      "type": "table_path",
    },
    "query_parameters": {
      "consistency": {
        "type": "string",
      },
      "datacenter": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "keyspace",
    },
    "schemes": [
      "cassandra",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "clickhouse",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 9000,
    },
    "id": "clickhouse",
    "name": "ClickHouse",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "createDatabaseIfNotExist": {
        "type": "boolean",
      },
      "database": {
        "type": "string",
      },
      "debug": {
        "type": "boolean",
      },
      "httpProtocol": {
        "allowed": [
          "http",
          "https",
        ],
        "type": "string",
      },
      "password": {
        "type": "string",
      },
      "readonly": {
        "type": "number",
      },
      "ssl": {
        "type": "boolean",
      },
      "sslmode": {
        "allowed": [
          "disable",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
      "user": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "clickhouse",
      "ch",
    ],
    "semantic_fields": {
      "debug": {
        "sources": [
          {
            "from_query": "debug",
            "values": {
              "false": False,
              "true": True,
            },
          },
        ],
      },
      "http_protocol": {
        "sources": [
          {
            "from_query": "httpProtocol",
          },
          {
            "from_option": "protocol",
            "values": {
              "http": "http",
              "https": "https",
            },
          },
        ],
      },
      "readonly": {
        "sources": [
          {
            "from_query": "readonly",
          },
        ],
      },
      "ssl_mode": {
        "sources": [
          {
            "from_query": "sslmode",
            "values": {
              "disable": "disabled",
              "require": "required",
              "verify-ca": "verify-ca",
              "verify-full": "verify-identity",
            },
          },
          {
            "from_query": "ssl",
            "values": {
              "false": "disabled",
              "true": "enabled",
            },
          },
          {
            "from_option": "protocol",
            "values": {
              "http": "disabled",
              "https": "enabled",
            },
          },
        ],
      },
    },
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 26257,
    },
    "id": "cockroachdb",
    "name": "CockroachDB",
    "options": {
      "compatible_with": "postgres",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "application_name": {
        "type": "string",
      },
      "options": {
        "type": "string",
      },
      "password": {
        "type": "string",
      },
      "results_buffer_size": {
        "type": "string",
      },
      "sslcert": {
        "type": "string",
      },
      "sslkey": {
        "type": "string",
      },
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
      "sslrootcert": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "sslcert",
        "sslkey",
        "sslrootcert",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "cockroach",
      "cockroachdb",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5432,
    },
    "id": "cratedb",
    "name": "CrateDB",
    "options": {
      "compatible_with": "postgres",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "cratedb",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 443,
    },
    "id": "databricks",
    "name": "Databricks",
    "path": {
      "required": False,
      "type": "http_path",
    },
    "query_parameters": {
      "access_token": {
        "type": "string",
      },
      "http_path": {
        "type": "string",
      },
      "warehouse": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
        "access_token",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "databricks",
    ],
    "type": "analytics",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 50000,
    },
    "id": "db2",
    "name": "IBM Db2",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {},
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "db2",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mongodb",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 27017,
    },
    "id": "documentdb",
    "name": "Amazon DocumentDB",
    "options": {
      "compatible_with": "mongodb",
      "provider": "aws",
    },
    "path": {
      "required": False,
      "type": "collection",
    },
    "query_parameters": {
      "authSource": {
        "type": "string",
      },
      "readPreference": {
        "type": "string",
      },
      "replicaSet": {
        "type": "string",
      },
      "retryWrites": {
        "type": "boolean",
      },
      "tls": {
        "type": "boolean",
      },
      "tlsCAFile": {
        "type": "string",
      },
      "tlsCertificateKeyFile": {
        "type": "string",
      },
      "tlsInsecure": {
        "type": "boolean",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "tlsCAFile",
        "tlsCertificateKeyFile",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "documentdb",
      "documentdb+srv",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "redis",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 6379,
    },
    "id": "dragonfly",
    "name": "Dragonfly",
    "options": {
      "compatible_with": "redis",
    },
    "path": {
      "required": False,
      "type": "none",
    },
    "query_parameters": {
      "protocol": {
        "type": "number",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database_index",
    },
    "schemes": [
      "dragonfly",
      "dragonflys",
    ],
    "type": "cache",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "duckdb",
    "authority": {},
    "credentials": {},
    "id": "duckdb",
    "name": "DuckDB",
    "path": {
      "required": True,
      "type": "filesystem_path",
    },
    "query_parameters": {
      "access_mode": {
        "type": "string",
      },
    },
    "resource": {
      "required": True,
      "type": "database",
    },
    "schemes": [
      "duckdb",
    ],
    "type": "database",
    "validation": {},
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 1433,
    },
    "id": "dynamicsnav",
    "name": "Dynamics NAV",
    "options": {
      "compatible_with": "mssql",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "auth_method": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "company",
    },
    "schemes": [
      "dynamicsnav",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "region": True,
    },
    "credentials": {
      "access_key": True,
      "password": True,
      "secret_key": True,
      "token": True,
      "username": True,
    },
    "id": "dynamodb",
    "name": "DynamoDB",
    "path": {
      "required": False,
      "type": "item_path",
    },
    "query_parameters": {
      "profile": {
        "type": "string",
      },
      "region": {
        "type": "string",
      },
      "token": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "access_key",
        "secret_key",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "table",
    },
    "schemes": [
      "dynamodb",
    ],
    "type": "database",
    "validation": {
      "require_host": False,
    },
  },
  {
    "adapter": "redis",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 6379,
    },
    "id": "elasticache",
    "name": "Amazon ElastiCache",
    "options": {
      "compatible_with": "redis",
      "provider": "aws",
      "tls": True,
    },
    "path": {
      "required": False,
      "type": "none",
    },
    "query_parameters": {
      "protocol": {
        "type": "number",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database_index",
    },
    "schemes": [
      "elasticache",
      "elasticaches",
    ],
    "type": "cache",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "elasticsearch",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "api_key": True,
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 9200,
    },
    "id": "elasticsearch",
    "name": "Elasticsearch",
    "path": {
      "required": False,
      "type": "api_path",
    },
    "query_parameters": {
      "api_key": {
        "aliases": [
          "apiKey",
        ],
        "type": "string",
      },
      "token": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "api_key",
        "apiKey",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "index",
    },
    "schemes": [
      "elasticsearch",
      "elastic",
      "elasticsearch+http",
      "elasticsearch+https",
    ],
    "semantic_fields": {
      "ssl_mode": {
        "sources": [
          {
            "from_option": "tls",
            "values": {
              "false": "disabled",
              "true": "enabled",
            },
          },
        ],
      },
    },
    "type": "api",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mongodb",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 27017,
    },
    "id": "ferretdb",
    "name": "FerretDB",
    "options": {
      "compatible_with": "mongodb",
    },
    "path": {
      "required": False,
      "type": "collection",
    },
    "query_parameters": {
      "authSource": {
        "type": "string",
      },
      "replicaSet": {
        "type": "string",
      },
      "retryWrites": {
        "type": "boolean",
      },
      "tls": {
        "type": "boolean",
      },
      "tlsCAFile": {
        "type": "string",
      },
      "tlsCertificateKeyFile": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "tlsCAFile",
        "tlsCertificateKeyFile",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "ferretdb",
      "ferretdb+srv",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "file",
    "authority": {
      "host": False,
    },
    "credentials": {},
    "id": "file",
    "name": "File",
    "path": {
      "required": True,
      "type": "filesystem_path",
    },
    "query_parameters": {},
    "resource": {
      "required": False,
      "type": "none",
    },
    "schemes": [
      "file",
    ],
    "type": "file",
    "validation": {},
  },
  {
    "adapter": "mongodb",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 443,
    },
    "id": "firestore",
    "name": "Firestore",
    "options": {
      "compatible_with": "mongodb",
      "provider": "gcp",
    },
    "path": {
      "required": False,
      "type": "collection",
    },
    "query_parameters": {
      "database": {
        "type": "string",
      },
      "project": {
        "type": "string",
      },
      "token": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "firestore",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5432,
    },
    "id": "gaussdb",
    "name": "GaussDB",
    "options": {
      "compatible_with": "postgres",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "application_name": {
        "type": "string",
      },
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "gaussdb",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "object-storage",
    "authority": {
      "bucket": True,
      "project": True,
    },
    "credentials": {
      "token": True,
    },
    "id": "gcs",
    "name": "Google Cloud Storage",
    "options": {
      "provider": "gcp",
    },
    "path": {
      "required": False,
      "type": "object_key",
    },
    "query_parameters": {
      "access_token": {
        "type": "string",
      },
      "generation": {
        "type": "string",
      },
      "project": {
        "type": "string",
      },
      "project_id": {
        "type": "string",
      },
      "projectId": {
        "type": "string",
      },
      "service_account_key_path": {
        "type": "string",
      },
      "userProject": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [],
      "sensitive_keys": [
        "token",
        "access_token",
      ],
    },
    "resource": {
      "required": True,
      "type": "bucket",
    },
    "schemes": [
      "gs",
      "gcs",
    ],
    "type": "object_storage",
    "validation": {},
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 9092,
    },
    "id": "h2",
    "name": "H2 Database",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {},
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "h2",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 3306,
    },
    "id": "mariadb",
    "name": "MariaDB",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "allowCleartextPasswords": {
        "type": "boolean",
      },
      "loc": {
        "type": "string",
      },
      "parseTime": {
        "type": "boolean",
      },
      "password": {
        "type": "string",
      },
      "ssl": {
        "type": "string",
      },
      "sslMode": {
        "aliases": [
          "ssl-mode",
        ],
        "allowed": [
          "disable",
          "trust",
          "verify-ca",
          "verify-full",
        ],
        "normalized_values": {
          "verify_ca": "verify-ca",
          "verify_full": "verify-full",
        },
        "type": "string",
      },
      "user": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "mariadb",
    ],
    "semantic_fields": {
      "allow_cleartext_passwords": {
        "sources": [
          {
            "from_query": "allowCleartextPasswords",
            "values": {
              "false": False,
              "true": True,
            },
          },
        ],
      },
      "loc": {
        "sources": [
          {
            "from_query": "loc",
          },
        ],
      },
      "parse_time": {
        "sources": [
          {
            "from_query": "parseTime",
            "values": {
              "false": False,
              "true": True,
            },
          },
        ],
      },
      "ssl_mode": {
        "sources": [
          {
            "from_query": "sslMode",
            "values": {
              "disable": "disabled",
              "trust": "insecure",
              "verify-ca": "verify-ca",
              "verify-full": "verify-identity",
            },
          },
        ],
      },
    },
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5432,
    },
    "id": "materialize",
    "name": "Materialize",
    "options": {
      "compatible_with": "postgres",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "materialize",
    ],
    "type": "analytics",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "memcached",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 11211,
    },
    "id": "memcached",
    "name": "Memcached",
    "path": {
      "required": False,
      "type": "none",
    },
    "query_parameters": {},
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "none",
    },
    "schemes": [
      "memcached",
      "memcacheds",
    ],
    "type": "cache",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 7687,
    },
    "id": "memgraph",
    "name": "Memgraph",
    "options": {
      "compatible_with": "neo4j",
      "model": "graph",
    },
    "path": {
      "required": False,
      "type": "graph_path",
    },
    "query_parameters": {},
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "memgraph",
      "memgraph+s",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "redis",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 6379,
    },
    "id": "memorydb",
    "name": "Amazon MemoryDB",
    "options": {
      "compatible_with": "redis",
      "provider": "aws",
      "tls": True,
    },
    "path": {
      "required": False,
      "type": "none",
    },
    "query_parameters": {
      "protocol": {
        "type": "number",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database_index",
    },
    "schemes": [
      "memorydb",
      "memorydbs",
    ],
    "type": "cache",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mongodb",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 27017,
    },
    "id": "mongodb",
    "name": "MongoDB",
    "path": {
      "required": False,
      "type": "collection",
    },
    "query_parameters": {
      "authMechanism": {
        "type": "string",
      },
      "authMechanismProperties": {
        "type": "string",
      },
      "authSource": {
        "type": "string",
      },
      "connectTimeoutMS": {
        "type": "number",
      },
      "directConnection": {
        "type": "boolean",
      },
      "replicaSet": {
        "type": "string",
      },
      "retryWrites": {
        "type": "boolean",
      },
      "serverSelectionTimeoutMS": {
        "type": "number",
      },
      "ssl": {
        "type": "boolean",
      },
      "tls": {
        "type": "boolean",
      },
      "tlsCAFile": {
        "type": "string",
      },
      "tlsCertificateKeyFile": {
        "type": "string",
      },
      "tlsInsecure": {
        "type": "boolean",
      },
      "w": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "tlsCAFile",
        "tlsCertificateKeyFile",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "mongodb",
      "mongodb+srv",
    ],
    "semantic_fields": {
      "dns_enabled": {
        "sources": [
          {
            "from_option": "srv",
          },
        ],
      },
      "ssl_mode": {
        "sources": [
          {
            "from_query": "tlsInsecure",
            "values": {
              "true": "insecure",
            },
          },
          {
            "from_query": "tls",
            "values": {
              "false": "disabled",
              "true": "enabled",
            },
          },
          {
            "from_query": "ssl",
            "values": {
              "false": "disabled",
              "true": "enabled",
            },
          },
        ],
      },
    },
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 1433,
    },
    "id": "mssql",
    "name": "Microsoft SQL Server",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "encrypt": {
        "type": "boolean",
      },
      "trustServerCertificate": {
        "type": "boolean",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "mssql",
      "sqlserver",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 3306,
    },
    "id": "mysql",
    "name": "MySQL",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "allowCleartextPasswords": {
        "type": "boolean",
      },
      "auth-method": {
        "allowed": [
          "AUTO",
          "MYSQL41",
          "SHA256_MEMORY",
          "FROM_CAPABILITIES",
          "FALLBACK",
          "PLAIN",
        ],
        "type": "string",
      },
      "charset": {
        "type": "string",
      },
      "get-server-public-key": {
        "type": "boolean",
      },
      "loc": {
        "type": "string",
      },
      "parseTime": {
        "type": "boolean",
      },
      "schema": {
        "type": "string",
      },
      "ssl": {
        "type": "string",
      },
      "ssl-ca": {
        "type": "string",
      },
      "ssl-capath": {
        "type": "string",
      },
      "ssl-cert": {
        "type": "string",
      },
      "ssl-cipher": {
        "type": "string",
      },
      "ssl-crl": {
        "type": "string",
      },
      "ssl-crlpath": {
        "type": "string",
      },
      "ssl-key": {
        "type": "string",
      },
      "ssl-mode": {
        "aliases": [
          "sslMode",
        ],
        "allowed": [
          "DISABLED",
          "PREFERRED",
          "REQUIRED",
          "VERIFY_CA",
          "VERIFY_IDENTITY",
        ],
        "normalized_values": {
          "disabled": "DISABLED",
          "preferred": "PREFERRED",
          "required": "REQUIRED",
          "verify_ca": "VERIFY_CA",
          "verify_identity": "VERIFY_IDENTITY",
          "verify-ca": "VERIFY_CA",
          "verify-identity": "VERIFY_IDENTITY",
        },
        "type": "string",
      },
      "tls-version": {
        "type": "string",
      },
      "tls-versions": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "ssl-ca",
        "ssl-capath",
        "ssl-cert",
        "ssl-cipher",
        "ssl-crl",
        "ssl-crlpath",
        "ssl-key",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "mysql",
      "mysqlx",
      "mysqlx+srv",
    ],
    "semantic_fields": {
      "allow_cleartext_passwords": {
        "sources": [
          {
            "from_query": "allowCleartextPasswords",
            "values": {
              "false": False,
              "true": True,
            },
          },
        ],
      },
      "loc": {
        "sources": [
          {
            "from_query": "loc",
          },
        ],
      },
      "parse_time": {
        "sources": [
          {
            "from_query": "parseTime",
            "values": {
              "false": False,
              "true": True,
            },
          },
        ],
      },
      "ssl_mode": {
        "sources": [
          {
            "from_query": "ssl-mode",
            "values": {
              "DISABLED": "disabled",
              "PREFERRED": "preferred",
              "REQUIRED": "required",
              "VERIFY_CA": "verify-ca",
              "VERIFY_IDENTITY": "verify-identity",
            },
          },
        ],
      },
    },
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 7687,
    },
    "id": "neo4j",
    "name": "Neo4j",
    "options": {
      "model": "graph",
    },
    "path": {
      "required": False,
      "type": "graph_path",
    },
    "query_parameters": {},
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "neo4j",
      "neo4j+s",
      "bolt",
      "bolt+s",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 8182,
    },
    "id": "neptune",
    "name": "Neptune",
    "options": {
      "model": "graph",
      "provider": "aws",
    },
    "path": {
      "required": False,
      "type": "graph_path",
    },
    "query_parameters": {},
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "graph",
    },
    "schemes": [
      "neptune",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 3306,
    },
    "id": "oceanbase",
    "name": "OceanBase",
    "options": {
      "compatible_with": "mysql",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "charset": {
        "type": "string",
      },
      "ssl": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "oceanbase",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "api_key": True,
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 9200,
    },
    "id": "opensearch",
    "name": "OpenSearch",
    "options": {
      "compatible_with": "elasticsearch",
    },
    "path": {
      "required": False,
      "type": "api_path",
    },
    "query_parameters": {
      "api_key": {
        "aliases": [
          "apiKey",
        ],
        "type": "string",
      },
      "token": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "api_key",
        "apiKey",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "index",
    },
    "schemes": [
      "opensearch",
      "opensearch+http",
      "opensearch+https",
    ],
    "semantic_fields": {
      "ssl_mode": {
        "sources": [
          {
            "from_scheme": True,
            "values": {
              "http": "disabled",
              "https": "enabled",
              "opensearch+http": "disabled",
              "opensearch+https": "enabled",
            },
          },
        ],
      },
    },
    "type": "api",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 1521,
    },
    "id": "oracle",
    "name": "Oracle",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "service_name": {
        "type": "string",
      },
      "sid": {
        "type": "string",
      },
      "wallet": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "wallet",
      ],
    },
    "resource": {
      "required": False,
      "type": "service",
    },
    "schemes": [
      "oracle",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5432,
    },
    "id": "postgres",
    "name": "PostgreSQL",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "application_name": {
        "type": "string",
      },
      "connect_timeout": {
        "type": "number",
      },
      "host": {
        "type": "string",
      },
      "hostaddr": {
        "type": "string",
      },
      "options": {
        "type": "string",
      },
      "passfile": {
        "type": "string",
      },
      "password": {
        "type": "string",
      },
      "port": {
        "type": "string",
      },
      "require_auth": {
        "type": "string",
      },
      "search_path": {
        "type": "string",
      },
      "service": {
        "type": "string",
      },
      "sslcert": {
        "type": "string",
      },
      "sslkey": {
        "type": "string",
      },
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
      "sslrootcert": {
        "type": "string",
      },
      "target_session_attrs": {
        "allowed": [
          "any",
          "read-write",
          "read-only",
          "primary",
          "standby",
          "prefer-standby",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "passfile",
        "sslcert",
        "sslkey",
        "sslrootcert",
      ],
    },
    "resource": {
      "required": True,
      "type": "database",
    },
    "schemes": [
      "postgres",
      "postgresql",
    ],
    "semantic_fields": {
      "search_path": {
        "sources": [
          {
            "from_query": "search_path",
          },
        ],
      },
      "ssl_mode": {
        "sources": [
          {
            "from_query": "sslmode",
            "values": {
              "disable": "disabled",
              "require": "required",
              "verify-ca": "verify-ca",
              "verify-full": "verify-identity",
            },
          },
        ],
      },
    },
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "questdb",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 8812,
    },
    "id": "questdb",
    "name": "QuestDB",
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "auto_flush": {
        "allowed": [
          "on",
          "off",
        ],
        "type": "string",
      },
      "auto_flush_interval": {
        "type": "number",
      },
      "auto_flush_rows": {
        "type": "number",
      },
      "init_buf_size": {
        "type": "number",
      },
      "max_buf_size": {
        "type": "number",
      },
      "protocol_version": {
        "type": "string",
      },
      "request_min_throughput": {
        "type": "number",
      },
      "request_timeout": {
        "type": "number",
      },
      "retry_timeout": {
        "type": "number",
      },
      "tls_roots": {
        "type": "string",
      },
      "tls_roots_password": {
        "type": "string",
      },
      "tls_verify": {
        "allowed": [
          "on",
          "unsafe_off",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
        "tls_roots_password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "questdb",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "redis",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 6379,
    },
    "id": "redis",
    "name": "Redis",
    "path": {
      "required": False,
      "type": "none",
    },
    "query_parameters": {
      "protocol": {
        "type": "number",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database_index",
    },
    "schemes": [
      "redis",
      "rediss",
    ],
    "semantic_fields": {
      "ssl_mode": {
        "sources": [
          {
            "from_option": "tls",
            "values": {
              "false": "disabled",
              "true": "enabled",
            },
          },
        ],
      },
    },
    "type": "cache",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5439,
    },
    "id": "redshift",
    "name": "Redshift",
    "options": {
      "compatible_with": "postgres",
      "provider": "aws",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "redshift",
    ],
    "type": "analytics",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5432,
    },
    "id": "risingwave",
    "name": "RisingWave",
    "options": {
      "compatible_with": "postgres",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "risingwave",
    ],
    "type": "stream",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "s3",
    "authority": {
      "bucket": True,
      "region": True,
    },
    "credentials": {},
    "id": "s3",
    "name": "Amazon S3",
    "path": {
      "required": False,
      "type": "object_key",
    },
    "query_parameters": {
      "region": {
        "type": "string",
      },
      "versionId": {
        "type": "string",
      },
    },
    "resource": {
      "required": True,
      "type": "bucket",
    },
    "schemes": [
      "s3",
    ],
    "type": "object_storage",
    "validation": {},
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 30015,
    },
    "id": "saphana",
    "name": "SAP HANA",
    "path": {
      "required": False,
      "type": "schema_path",
    },
    "query_parameters": {
      "auth_method": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "saphana",
      "hana",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 3306,
    },
    "id": "singlestore",
    "name": "SingleStore",
    "options": {
      "compatible_with": "mysql",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "charset": {
        "type": "string",
      },
      "ssl": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "singlestore",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 443,
    },
    "id": "snowflake",
    "name": "Snowflake",
    "path": {
      "required": False,
      "type": "schema_path",
    },
    "query_parameters": {
      "role": {
        "type": "string",
      },
      "schema": {
        "type": "string",
      },
      "token": {
        "type": "string",
      },
      "warehouse": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "snowflake",
    ],
    "type": "analytics",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "project": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "id": "spanner",
    "name": "Spanner",
    "path": {
      "required": False,
      "type": "database_path",
    },
    "query_parameters": {
      "database": {
        "type": "string",
      },
      "instance": {
        "type": "string",
      },
      "project": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "instance",
    },
    "schemes": [
      "spanner",
    ],
    "type": "database",
    "validation": {
      "require_host": True,
    },
  },
  {
    "adapter": "sqlite",
    "authority": {},
    "credentials": {},
    "id": "sqlite",
    "name": "SQLite",
    "path": {
      "required": True,
      "type": "filesystem_path",
    },
    "provider_aliases": [
      "sqlite3",
    ],
    "query_parameters": {
      "cache": {
        "type": "string",
      },
      "mode": {
        "type": "string",
      },
    },
    "resource": {
      "required": True,
      "type": "database",
    },
    "schemes": [
      "sqlite",
    ],
    "type": "database",
    "validation": {},
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 9030,
    },
    "id": "starrocks",
    "name": "StarRocks",
    "options": {
      "compatible_with": "mysql",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "charset": {
        "type": "string",
      },
      "ssl": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "starrocks",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {},
    "defaults": {
      "port": 9000,
    },
    "id": "tallyprime",
    "name": "TallyPrime",
    "path": {
      "required": False,
      "type": "collection_path",
    },
    "query_parameters": {},
    "resource": {
      "required": False,
      "type": "company",
    },
    "schemes": [
      "tally",
      "tallyprime",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "mysql-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 4000,
    },
    "id": "tidb",
    "name": "TiDB",
    "options": {
      "compatible_with": "mysql",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "allowCleartextPasswords": {
        "type": "boolean",
      },
      "charset": {
        "type": "string",
      },
      "loc": {
        "type": "string",
      },
      "parseTime": {
        "type": "boolean",
      },
      "ssl": {
        "type": "string",
      },
      "ssl-mode": {
        "aliases": [
          "sslMode",
        ],
        "allowed": [
          "DISABLED",
          "PREFERRED",
          "REQUIRED",
          "VERIFY_CA",
          "VERIFY_IDENTITY",
        ],
        "normalized_values": {
          "disabled": "DISABLED",
          "preferred": "PREFERRED",
          "required": "REQUIRED",
          "verify_ca": "VERIFY_CA",
          "verify_identity": "VERIFY_IDENTITY",
          "verify-ca": "VERIFY_CA",
          "verify-identity": "VERIFY_IDENTITY",
        },
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "tidb",
    ],
    "semantic_fields": {
      "allow_cleartext_passwords": {
        "sources": [
          {
            "from_query": "allowCleartextPasswords",
            "values": {
              "false": False,
              "true": True,
            },
          },
        ],
      },
      "loc": {
        "sources": [
          {
            "from_query": "loc",
          },
        ],
      },
      "parse_time": {
        "sources": [
          {
            "from_query": "parseTime",
            "values": {
              "false": False,
              "true": True,
            },
          },
        ],
      },
      "ssl_mode": {
        "sources": [
          {
            "from_query": "ssl-mode",
            "values": {
              "DISABLED": "disabled",
              "PREFERRED": "preferred",
              "REQUIRED": "required",
              "VERIFY_CA": "verify-ca",
              "VERIFY_IDENTITY": "verify-identity",
            },
          },
        ],
      },
    },
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "region": True,
    },
    "credentials": {
      "access_key": True,
      "password": True,
      "secret_key": True,
      "token": True,
      "username": True,
    },
    "id": "timestream",
    "name": "Timestream",
    "path": {
      "required": False,
      "type": "table_path",
    },
    "query_parameters": {
      "region": {
        "type": "string",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "access_key",
        "secret_key",
        "token",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "timestream",
    ],
    "type": "analytics",
    "validation": {
      "require_host": False,
    },
  },
  {
    "adapter": "generic-uri",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "token": True,
      "username": True,
    },
    "defaults": {
      "port": 8080,
    },
    "id": "trino",
    "name": "Trino",
    "path": {
      "required": False,
      "type": "schema_path",
    },
    "query_parameters": {
      "accessToken": {
        "type": "string",
      },
      "SSL": {
        "type": "boolean",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "token",
        "accessToken",
      ],
    },
    "resource": {
      "required": False,
      "type": "catalog",
    },
    "schemes": [
      "trino",
    ],
    "type": "analytics",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "redis",
    "authority": {
      "host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 6379,
    },
    "id": "valkey",
    "name": "Valkey",
    "options": {
      "compatible_with": "redis",
    },
    "path": {
      "required": False,
      "type": "none",
    },
    "query_parameters": {
      "protocol": {
        "type": "number",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
      ],
    },
    "resource": {
      "required": False,
      "type": "database_index",
    },
    "schemes": [
      "valkey",
      "valkeys",
    ],
    "type": "cache",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
  {
    "adapter": "postgres-compatible",
    "authority": {
      "host": True,
      "multi_host": True,
      "port": True,
    },
    "credentials": {
      "password": True,
      "username": True,
    },
    "defaults": {
      "port": 5433,
    },
    "id": "yugabytedb",
    "name": "YugabyteDB",
    "options": {
      "compatible_with": "postgres",
    },
    "path": {
      "required": False,
      "type": "object_path",
    },
    "query_parameters": {
      "loadBalance": {
        "type": "string",
      },
      "ssl": {
        "type": "boolean",
      },
      "sslmode": {
        "allowed": [
          "disable",
          "allow",
          "prefer",
          "require",
          "verify-ca",
          "verify-full",
        ],
        "type": "string",
      },
      "sslrootcert": {
        "type": "string",
      },
      "topologyKeys": {
        "type": "string",
      },
      "ybServersRefreshInterval": {
        "type": "number",
      },
    },
    "redaction": {
      "safe_credentials": [
        "username",
      ],
      "sensitive_keys": [
        "password",
        "sslrootcert",
      ],
    },
    "resource": {
      "required": False,
      "type": "database",
    },
    "schemes": [
      "yugabyte",
      "yugabytedb",
    ],
    "type": "database",
    "validation": {
      "port_range": {
        "max": 65535,
        "min": 1,
      },
      "require_host": True,
    },
  },
]
